apiVersion: apps/v1
kind: Deployment
metadata:
  name: audioshelf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audioshelf
  template:
    metadata:
      labels:
        app: audioshelf
    spec:

      containers:
        - name: audioshelf
          image: ghcr.io/advplyr/audiobookshelf:latest
          ports:
            - containerPort: 3005
          envFrom:
            - configMapRef:
                name: audioshelf-configmap

          volumeMounts:
            - mountPath: /config
              name: audioshelf-config
            - mountPath: /metadata
              name: audioshelf-metadata
            - mountPath: /audiobooks
              name: audioshelf-audiobooks

      restartPolicy: Always
      volumes:
        - name: audioshelf-config
          persistentVolumeClaim:
            claimName: audioshelf-config-pvc
        - name: audioshelf-metadata
          persistentVolumeClaim:
            claimName: audioshelf-metadata-pvc
        - name: audioshelf-audiobooks
          persistentVolumeClaim:
            claimName: audioshelf-audiobooks-pvc
