apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audioshelf-config-pvc
  namespace: audioshelf
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audioshelf-metadata-pvc
  namespace: audioshelf
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audioshelf-audiobooks-pvc
  namespace: audioshelf
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

