apiVersion: v1
data:
    password: ENC[AES256_GCM,data:bRtWjzfyev8=,iv:3Lis8UodcWljOaX8ur13Myc9o0vBa0sUYrTP+z7KGAE=,tag:oSI0TST7HyjMbnNFqML66g==,type:str]
    user: ENC[AES256_GCM,data:i1t8G118WKc=,iv:yir4SVOduw/nQpTywez8IVBWWlUPZDqBq5jjCP2wj3E=,tag:i4OxvmjAN0ho+NIJncn9EA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: test-secret
sops:
    age:
        - recipient: age1p7k9ykk3dru6cw4gztjvl89te6y73jmehj6fp02g0ruq4dv5435qecmgwl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqWFhsc29Fc05SVk9xWWkr
            MlZpekN5b2Z6TCtEQmJSWUxTSEVFNFIyOHdRCnF5ZFdRZUN6R2FsTGNhNlAwM2xz
            VGpvVlBEdHpxVk4vWVhQUlVpbVVXMUUKLS0tIFpyT3BDRzNLd3JzcDU2VGhpZ3dn
            TWZGZnFlUjBwclFITS95dDdUUWhEWjQKoVzbJe17N61s9dnAdaeQbIEXXWo0bG3r
            2qLJ35bd1iy1i2foqZll13+LDL/q8eAQkJhpioLIsUivX9qWrnQnTQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-15T00:11:45Z"
    mac: ENC[AES256_GCM,data:+TjuYkXa+v3TmOI+dtJQV/vzdAdZWd9eFzcdWvHFBbrEGC8uuFkZk2JOP70tl3EOLTptBVEoG8f/e3IK+U+iELLG2g7yQNPCyvJZ69Q77ab3FC+NR+OpLszy8Ktkt727GKCItABkRq2zSP1b+dPZCiuuL+NybQrjtL2lZki2iVw=,iv:m5LQqAAzxmqEJuC5sWSuMX87yKFAcKpXwiFcaWP3tzw=,tag:4am1M/j2whF8HSiD+UuCXw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
