apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:Dxfbs+U2bZ7mKYTVmkaYPofiZ9kMCCzaScuXVDrkte82a/ZBVIE5NjbpYRC5chVJ/i7SzB6zXPAULdTWNdOm9lSciWci0PhkLNi7w/FE53x0vzGQI/1zY7h954/ZuiNioZCNRXYe0nUEOGUX9xjqi5bvXSohlb+cc4C9cHP1rfr+o2VMEIW12p95jPcYdiv8F9bvbQZRlC/WwrZU3ONuBEKABEnYW10YdN/quhkf3kTI10zRXUySw2BBExHt9Z76OzjjLsBJXAfogwfbQTQp6nR5Bept9sRCfKbqwQWmx7IH5BkZA2dAKhvMP1U=,iv:6i+/CrznW78g1595qv24Jthz6KhRlTp+AJiCRz9l3mM=,tag:LP6imOGLrkt7GNzCtDIM2A==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: tunnel-credentials
sops:
    age:
        - recipient: age1p7k9ykk3dru6cw4gztjvl89te6y73jmehj6fp02g0ruq4dv5435qecmgwl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2UHJ3ZExoZEkwMmJUYmJa
            L012NHd1d2M3VTZtR1FUcEYwSXFaKzdlS2xNCjdIMmNkUWE5NEE4TDJhdnJuYTJv
            NHdabFJCUkcxSWpyUWVNdGhqREJMREkKLS0tIDFkUGhsS05VZmhVWU1zeG5WMHFX
            ck5oNkdGVVRZWENia3FqeUdRcGloUzQKI8wizYc6i0otO6LB/ly/saokLvqzmG8R
            KE1oumx5y52W1qrRVYK8ffIkIHLnkiqtCcWYIeoCpS2poegCTMs/lg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-24T03:21:21Z"
    mac: ENC[AES256_GCM,data:AReGj1vH7aaJKSSDJKs/z1NNnXlgdCIheWFghpwvxUOhEJydntavg1/YnZs4FI0IhmuI7nuofRw3ybyCdLG1k2MVWEAx8rrMis58eFARk1GCASl7t4+I3kQs7BgJnIOY260mG1bPzqG5eB1hC08zVmb+ML1QaH7jYZfJVybrKIA=,iv:Yms1uvSdyRCZW3MrXqMqHV8WgR/H0lgefF1KTty09Z4=,tag:ItOiu6gvAHwsvPlNQV+Tuw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
